spring:
  application:
    name: mytoken-service-upload
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8505
fastdfs.base.url: http://192.168.110.137:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 192.168.110.137:22122

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info