spring:
  application:
    name: mytoken-service-redis
  boot:
    admin:
      client:
        url: http://192.168.110.138:8084
  zipkin:
    base-url: http://192.168.110.138:9411
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.110.141:26379,192.168.110.141:26380,192.168.110.141:26381
server:
  port: 8502


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info