spring:
  application:
    name: mytoken-config
  boot:
    admin:
      client:
        url: http://192.168.110.133:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/jucktoken/mytoken-config
          search-paths: respo
          username: 974674855@qq.com
          password: zhang10903
  zipkin:
    base-url: http://192.168.110.133:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.110.133:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info